[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NEXT_PUBLIC_BUILD_MODE = "true" # enable build-safe mocks
  MONGO_MOCK = "true"            # force mock DB client during SSG
  NEXT_PUBLIC_URL = "https://groqtales.xyz"
  MONGODB_URI = "mongodb://mock:mock@mock:27017/mock" # prevent SRV lookup
  MONGODB_DB_NAME = "mock-db"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_BUILD_MODE = "true"
  MONGO_MOCK = "true"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_BUILD_MODE = "true"
  MONGO_MOCK = "true"
