name: Sync Wiki Content

on:
  push:
    paths:
      - 'wiki/**'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync Wiki
        uses: newrelic/wiki-sync-action@v1.0.0
        with:
          source: wiki
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}